CREATE TABLE CAR (
	CAR_CODE varchar(20) NOT NULL COMMENT '자동차코드',  
	REG_DT datetime NOT NULL COMMENT '입력일시',  
	UPDATE_DT datetime NOT NULL COMMENT '수정일시',  
	PRIMARY KEY (CAR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='자동차'
;


CREATE TABLE CAR_MON_CNT (
	MON varchar(6) NOT NULL COMMENT '월',
	CAR_CODE varchar(20) NOT NULL COMMENT '자동차코드',  	
	CNT INT NOT NULL COMMENT '수량',
	REG_DT datetime NOT NULL COMMENT '입력일시',  
	UPDATE_DT datetime NOT NULL COMMENT '수정일시',  
	PRIMARY KEY (MON, CAR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='자동차별월별수량'
;



CREATE TABLE CAR_ITEM (
	CAR_CODE varchar(20) NOT NULL COMMENT '자동차코드',  
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  	
	REG_DT datetime NOT NULL COMMENT '입력일시',  	
	PRIMARY KEY (CAR_CODE, ITEM_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='자동차별부품'
;


CREATE TABLE ITEM (	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  	
	ITEM_NM varchar(200) NOT NULL COMMENT '부품명',  	
	ITEM_KIND varchar(50) NOT NULL COMMENT '구분',  	
	OEM_PRICE INT NOT NULL COMMENT 'OEM단가',  	
	AS_PRICE INT NOT NULL COMMENT 'AS단가',  		
	REG_DT datetime NOT NULL COMMENT '입력일시',  	
	UPDATE_DT datetime NOT NULL COMMENT '수정일시',  
	PRIMARY KEY (ITEM_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품'
;


CREATE TABLE ITEM_MON_RCAR (	
	R_SEQ BIGINT NOT NULL AUTO_INCREMENT COMMENT '일련번호',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  	
	MON varchar(6) NOT NULL COMMENT '월',  	
	CNT INT NOT NULL COMMENT '수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (R_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별월별RCAR수량'
;

CREATE TABLE ITEM_MON_AS (	
	A_SEQ BIGINT NOT NULL AUTO_INCREMENT COMMENT '일련번호',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  	
	MON varchar(6) NOT NULL COMMENT '월',  	
	CNT INT NOT NULL COMMENT '수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (A_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별월별AS수량'
;

CREATE TABLE ITEM_MON_CKD (	
	C_SEQ BIGINT NOT NULL AUTO_INCREMENT COMMENT '일련번호',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  	
	MON varchar(6) NOT NULL COMMENT '월',  	
	CNT INT NOT NULL COMMENT '수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (C_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별월별CKD수량'
;

CREATE TABLE ITEM_RCAR_SUM (	
	MON VARCHAR(6) NOT NULL COMMENT '월',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  		
	SUM_CNT INT NOT NULL COMMENT '집계수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (MON, ITEM_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별RCAR집계'
;


CREATE TABLE ITEM_AS_SUM (	
	MON VARCHAR(6) NOT NULL COMMENT '월',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  		
	SUM_CNT INT NOT NULL COMMENT '집계수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (MON, ITEM_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별RAS집계'
;



CREATE TABLE ITEM_CKD_SUM (	
	MON VARCHAR(6) NOT NULL COMMENT '월',  	
	ITEM_NO varchar(30) NOT NULL COMMENT '부품번호',  		
	SUM_CNT INT NOT NULL COMMENT '집계수량',  			
	REG_DT datetime NOT NULL COMMENT '입력일시',  		
	PRIMARY KEY (MON, ITEM_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부품별CKD집계'
;