spring:
  profiles: production
  product:
    name: PROD
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  datasource:
    mot-ds: 
      mot-type: mysql
      jdbc-url: jdbc:mysql://172.16.10.43/car
      username: n3n
      password: n3n1004#
      driver-class-name: org.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true       
      mybatis:
        mapper-locations: classpath*:mybatis/mapper/mariadb/**/*.xml 
        type-handlers-package: kr.co.n3n.smartcity.common.typehandler
        executor-type: batch        
          
server:
  port: 9020
  context-path: /
  session:
    timeout: 3600

  tomcat:
    max-threads: 10
    uri-encoding: UTF-8


  jsp-servlet:
    init-parameters:
      development: true
