spring:
  profiles: development
  product:
    name: DEV
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  devtools: 
    livereload: 
      enabled: true
  datasource:
    mot-ds: 
      mot-type: mysql
      jdbc-url: jdbc:mysql://localhost/car?serverTimezone=UTC
      username: root
      password: dkswjs0!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true       
      mybatis:
        mapper-locations: classpath*:mybatis/mapper/mariadb/**/*.xml 
        type-handlers-package: kr.co.n3n.smartcity.common.typehandler
        executor-type: batch
  servlet: 
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      location: C:\workspace\temp

      
   
server:
  port: 9020
  context-path: /
  session:
    timeout: 3600

  tomcat:
    max-threads: 1024
    uri-encoding: UTF-8


carfile:
  targetpath: /home/car/tomcat/webapps/car